web_app/config/routes.rb
WebApp::Application.routes.draw do
  get "users/new"

  root to:  'static_pages#home'

  match "/signup",  to: 'users#new',            via: 'get'

  match "/careers", to: 'static_pages#careers', via: 'get'

  match "/about",   to: 'static_pages#about',   via: 'get'

  match "/contact", to: 'static_pages#contact', via: 'get'

end

web_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

web_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def careers
  end

  def about
  end

  def contact
  end
end

web_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

web_app/app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Advisicon"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

web_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

web_app/app/helpers/users_helper.rb
module UsersHelper
end

web_app/app/views/layouts/_accordian-ads.html.erb
<!--
<div id='accordianAds'>
  <ul class='accordion1'>
    <li class='five'>
      <%= image_tag 'app-dev-slide.jpg',  border: '0',
                                          alt: 'We offer custom Application Development',
                                          usemap: '#slide5' %>
    </li>
    -->
                                        <!-- END five -->
    <!--
    <li class='two'>
      <%= image_tag 'training-slide.jpg', border: '0',
                                          alt: 'We offer comprehensive training programs',
                                          usemap: '#slide4' %>
                                        </li>-->
                                        <!-- END two -->
    <!--
    <li class='one'>
      <img border='0' src='pix/slide3.jpg'  
           alt='We specialize in SharePoint' 
           usemap='#slide3' />
         </li>--><!-- END one -->
    <!--
    <li class='three'>
      <img border='0' src='pix/slide2.jpg'  
           alt='We can set up Microsoft Project and Microsoft Project Server' 
           usemap='#slide2' />
         </li>--><!-- END three -->
    <!--
    <li class='four'>
      <img border='0' src='pix/slide1.jpg' 
           alt='We deliver project, program, and portfolio management consulting services'
           usemap='#slide1' />
      <map name='slide1' id='slide1'>
        <area shape='rect' coords='303,203,399,245' 
              href='/project-management.htm' alt='project management slide' />
      </map>
      <map name='slide2' id='slide2'>
        <area shape='rect' coords='331,187,427,229' 
              href='/microsoft-project-office.htm' alt='microsoft project office slide' />
      </map>
      <map name='slide3' id='slide3'>
        <area shape='rect' coords='341,208,437,250' 
              href='/sharepoint.htm' alt='sharepoint slide' />
      </map>
      <map name='slide4' id='slide4'>
        <area shape='rect' coords='341,206,437,248' 
              href='/training.htm' alt='training slide' />
      </map>
      <map name='slide5' id='slide5'>
        <area shape='rect' coords='302,195,398,237' 
              href='/application_development.htm' alt='application development slide' />
      </map>
    </li>--><!-- END four -->
  </ul>--><!-- END accordion1 -->
</div>--><!-- END accordianAds -->

web_app/app/views/layouts/_bottom-scripts.html.erb
<script src='http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js'></script>
<script type='text/javascript'>
window.jQuery || document.write("<script src='jquery-1.6.0.min' type='text/javascript'>")
</script>
<%= javascript_include_tag "plugins" %>
<%= javascript_include_tag "script" %>
<script src='https://www.google.com/jsapi' 
        type='text/javascript'>
</script>
<%= javascript_include_tag "twitter" %>
<%= javascript_include_tag "jquery.easing.1.3" %>
<%= javascript_include_tag "jquery.hslides" %>
<%= javascript_include_tag "jquery.innerfade" %>
<%= javascript_include_tag "frontPageSlideshowHeader" %>
<%= javascript_include_tag "featuredProducts" %>
<%= javascript_include_tag "googlePlusOneButton" %>
<%= javascript_include_tag "rootGoogleAnalytics" %>

web_app/app/views/layouts/_carousel.html.erb
<div id="carousel-slideshow" class="carousel slide">
  <div class="carousel-inner">
    <div class="item active">
      <div class="fill" style="background-image:url(<%= asset_path 'headache.jpg' %>);">
        <div class="carousel-caption">
          <h3>Is your business a project management headache?</h3>
          <p>
            Advisicon delivers professional best practices-based project, 
            program, and portfolio management consulting services throughout
            the United States and Latin America to enable organizations to get 
            control over work management.
          </p>
          <p>
            <%= link_to "read more", '#', class: "btn btn-default" %>
          </p>
          <small>Image &copy; <a href="http://flic.kr/p/ftNmXV">Red River Furnace</a></small>
        </div>
      </div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url(<%= asset_path 'setup.jpg' %>);">
        <div class="carousel-caption">
          <h3>Setting up Project & Project Server</h3>
          <p>
            Advisicon consultants and subject matter experts are uniquely 
            qualified to partner with companies that are deploying Microsoft 
            Project, Microsoft Project/Portfolio Server and SharePoint in 
            support of a Project Management Office (PMO).
          </p>
          <p>
            <%= link_to "read more", '#', class: "btn btn-default" %>
          </p>
          <small>Image cc: <a href="http://flic.kr/p/6D4dUd">Dave Gough</a></small>
        </div>
      </div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url(<%= asset_path 'sharing.jpg' %>);">
        <div class="carousel-caption">
          <h3>We specialize in SharePoint</h3>
          <p>
            Advisicon provides end-to-end Microsoft&reg; SharePoint consulting 
            services. Based on our proven organizational work management 
            approach, we enable companies to configure, adopt and leverage the
            benefits of a collaboration technology and project management methodlogy.
          </p>
          <p>
            <%= link_to "read more", '#', class: "btn btn-default" %>
          </p>
          <small>Image cc: <a href="http://flic.kr/p/7YVszp">Ben Grey</a></small>
        </div>
      </div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url(<%= asset_path 'learn.jpg' %>);">
        <div class="carousel-caption">
          <h3>We offer comprehensive training programs</h3>
          <p>
            Advisicon delivers customized, consultatie instructor-led project 
            managmement training based on project management best practices on 
            the following topics using Advisicon's proprietary course manuals, 
            process flowcharts, and electronic tools and templates.
          </p>
          <p>
            <%= link_to "read more", '#', class: "btn btn-default" %>
          </p>
          <small>Image cc: <a href="http://flic.kr/p/gJjemL">Miroslav Vajdic</a></small>
        </div>
      </div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url(<%= asset_path 'code.jpg' %>);">
        <div class="carousel-caption">
          <h3>We offer custom application development</h3>
          <p>
            Advisicon develops custom applications and code to help 
            organizations achieve their business objectives, from integrating 
            EPM with other SQL-based systems, to custom code and databases, to 
            custom ERP integrations.
          </p>
          <p>
            <%= link_to "read more", '#', class: "btn btn-default" %>
          </p>
          <small>Image cc: <a href="http://flic.kr/p/9WUpmp">Elliot Cable</a></small>
        </div>
      </div>
    </div>
  </div><!-- END .carousel-inner -->
  <a class="carousel-control left" href="#carousel-slideshow" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="carousel-control right" href="#carousel-slideshow" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

web_app/app/views/layouts/_chromeframe.html.erb
<!--[if lt IE 8]>
  <p class='chromeframe'>Your browser is <em>ancient!</em> 
    <a href='http://browsehappy.com/'>Upgrade to a different browser</a> or 
    <a href='http://www.google.com/chromeframe/?redirect=true'>install Google Chrome Frame</a> 
    to experience this site.
  </p>
<![endif]-->

web_app/app/views/layouts/_course-ticker.html.erb
<div class='rPopBox'>
  <h3>Current Course Listings</h3>
  <div>
    <ul class='courses'></ul>
    <p>For course information and schedules contact us by phone at 
      <a href="tel:+1-360-314-6702" 
         class="tel" 
         title="call our Vancouver, WA office" 
         onclick="_gaq.push(['_trackEvent', 
                             'Phone Calls', 
                             'Headquarters', 
                             'Local']);">360.314.6702</a> 
      or email us at <a href="mailto:info@advisicon.com?subject=Question%20about%20Courses" 
        title="email us" 
        onclick="_gaq.push(['_trackEvent', 'Emails', 'Corporate', 'Inquiry']);">info@advisicon.com</a>
    </p>
  </div>
</div>

web_app/app/views/layouts/_credentials.html.erb
<!--
<ul id='credentials'>
  <li>
    <a href='/staff_bios/tim-runcie.htm' title='Learn more about Advisicon&rsquo;s President, Tim Runcie, a Microsoft MVP'>
      <img border='0' src='/pix/MVP_Horizontal_FullColor-small.jpg' alt='Microsoft MVP' width='150' height='53' />
    </a>
  </li>
  <li>
    <a href='/our-certifications.htm' title='Learn more about our competencies as a Microsoft Certified Partner'>
      <img border='0' src='/pix/microsoft-partner.png' alt='Microsoft Certified Gold Partner in Project and Portfolio Management, Silver Partner in Midmarket Solution Provider' width='150' height='54' />
    </a>
  </li>
  <li>
    <a href='http://www.pmi.org/' title='The PMI website'>
      <img border='0' src='/pix/logos/PMI-REP-logo.png' alt='Project Management Institute / Registered Education Provider' width='150' /> 
    </a>
  </li>
</ul>--><!-- END credentials --><!--
<div class='footnotes'>
  <p> 
    The PMI Registered Education Provider logo is a registered mark of the Project Management Institute, Inc.
  </p>
</div>--><!-- END footnotes -->

web_app/app/views/layouts/_featured-books.html.erb
<div class='rPopBox' id='featuredBooks'>
  <h3>Featured Books</h3>
  <ul id='portfolio'>
    <li>
      <a href='http://store.advisicon.com/products/microsoft-access-in-a-sharepoint-world'>--><!-- add event tracking to this link --><!--
        <img border='0' 
             src='/pix/Cover-MASW.jpg' 
             alt='Microsoft Access in a SharePoint World'
             width='150'
             height='195' />
      </a>
    </li>
    <li>
      <a href='http://store.advisicon.com/products/microsoft-business-intelligence-building-executive-dashboards-with-sharepoint-2010'>--><!-- add event tracking to this link --><!--
        <img border='0'
             src='/pix/Cover-BI-thumb.png'
             alt='Microsoft Business Intelligence' 
             width='150' 
             height='195' />
      </a>
    </li>
    <li>
      <a href='http://store.advisicon.com/products/microsoft-project-server-2010-administrators-guide'>--><!-- add event tracking to this link --><!--
        <img border='0' 
             src='/pix/Cover-MSPS2010-Admin.jpg' 
             alt='Microsoft Project Server 2010&nbsp;&ndash; Administrator&rsquo;s Guide' 
             width='150' 
             height='195' />
      </a>
    </li>
    <li>
      <a href='http://store.advisicon.com/products/microsoft-project-server-2010-project-managers-guide'>--><!-- add event tracking to this link --><!--
        <img border='0' 
             src='/pix/Cover-MSPS2010-PM.jpg' 
             alt='Microsoft Project Server 2010&nbsp;&ndash; Project Manager&rsquo;s Guide' 
             width='150'
             height='195' />
      </a>
    </li>
    <li>
      <a href='http://store.advisicon.com/products/microsoft-project-server-2010-team-members-guide'>
        <img border='0' 
             src='/pix/Cover-MSPS2010-TM.jpg' 
             alt='Microsoft Project Server 2010&nbsp;&ndash; Team Member&rsquo;s Guide' 
             width='150' 
             height='195' />
      </a>
    </li>
    <li>
      <a href='http://store.advisicon.com/products/managing-projects-with-microsoft-project-2010-best-practices-in-managing-projects-with-microsoft-project'>
        <img border='0' 
             src='/pix/Cover-MPWMSP2010.jpg' 
             alt='Managing Projects with Microsoft Project 2010' 
             width='150' 
             height='195' />
      </a>
    </li>
    <li>
      <a href='http://store.advisicon.com/products/sharepoint-for-effective-team-collaboration-2010'>
        <img border='0' 
             src='/pix/Cover-SPfETC-thumb.jpg' 
             alt='SharePoint for Effective Team Collaboration' 
             width='150' 
             height='195' />
      </a>
    </li>
  </ul>--><!-- END portfolio --><!--
  <p>Click a book for more information</p>
</div>

web_app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Sign In", '#' %> 
  </small>
  <nav>
    <ul>
      <li><%= link_to "Site Map", '#' %></li>
      <li><%= link_to "Privacy Policy", '#' %></li>
      <li>
        <a href='tel:+1-866-362-3847' 
           class='tel' 
           title='call us at 1-866-362-3847' 
           onclick="_gaq.push(['_trackEvent', 
                               'Phone Calls', 
                               'Headquarters', 
                               'Toll Free']);">1.866.36.ADVIS</a>
      </li>
    </ul>
  </nav>
</footer>

web_app/app/views/layouts/_google-verify.html.erb
<meta name='google-site-verification' content='jdLTywbexVH-8P7WmQp_agAuQGsl84-3bwwHwlrAtbs' >
<meta name='verify-v1'                content='Mn4HP1CuzeMuTt3AIDZiBOhx9QSkzo2pDByQ1HaTMKk=' >

web_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Advisicon", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">About <b class="caret"></b></a>
            <ul id="about-dropdown" class="dropdown-menu">
              <li><%= link_to "About Us",       about_path   %></li>
              <li><%= link_to "Contact",        contact_path %></li>
              <li><%= link_to "Careers",        careers_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Case Studies",   '#' %></li>
              <li><%= link_to "Clients",        '#' %></li>
              <li><%= link_to "Partners",       '#' %></li>
              <li><%= link_to "Professional Associations", '#' %></li>
              <li><%= link_to "Certifications", '#' %></li>
            </ul>
          </li>
          <li><%= link_to "Blog",    'http://blog.advisicon.com/' %></li>
          <li><%= link_to "Store",   'http://store.advisicon.com/' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Capabilities <b class="caret"></b></a>
            <ul id="capabilities-dropdown" class="dropdown-menu">
              <li><%= link_to "Application Development",  '#' %></li>
              <li><%= link_to "Training",                 '#' %></li>
              <li><%= link_to "SharePoint",               '#' %></li>
              <li><%= link_to "Project & Project Server", '#' %></li>
              <li><%= link_to "Project Management",       '#' %></li>
            </ul>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</header>

web_app/app/views/layouts/_news-ticker.html.erb
<div class='rPopBox'>
  <h3>News &amp; Events</h3>
  <ul>
    -->
    <!-- progromatically pull news from blog here -->
    <!-- formerly in vbscript. use ruby! -->
    <!--
  </ul>
</div>

web_app/app/views/layouts/_project-online-advert.html.erb
<div class='advert project'>
  <a href='/online/project-online.aspx'>
    <h3>Free Project Online Trial</h3>
    <p>Sign up for a Project Online trial!</p>
  </a>
</div>

web_app/app/views/layouts/_secondary-nav.html.erb
<!--
<nav id='secondaryNav'>
  <%= link_to "Case Studies", '#', class: 'secondaryNavButton' %>
  <%= link_to "Clients",      '#', class: 'secondaryNavButton' %>
  <%= link_to "Partners",     '#', class: 'secondaryNavButton' %>
  <%= link_to "Training",     '#', class: 'secondaryNavButton' %>
  <%= link_to "Store",        '#', class: 'secondaryNavButton' %>
  <%= link_to "Professional Associations", '#', class: 'secondaryNavButton longText' %>
  <%= link_to "News &amp; Events",         '#', class: 'secondaryNavButton' %>
  <%= link_to "Advisicon Public Course Schedule", '#', class: 'secondaryNavButton highlightedNavButton' %>
  <%= link_to "Contact Us!",  '#', class: 'secondaryNavButton highlightedNavButton' %>
</nav>--><!-- END secondary nav -->

web_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>

  <meta name='viewport'                 content='width=device-width, initial-scale=1.0' >
  <meta name='keywords'                 content="<%= yield(:keywords) %>" >
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <%= render 'layouts/shim' %>

</head>
<body>
  <%= render 'layouts/header' %>
  <%= render 'layouts/carousel' if @carousel  %>
  
  <div class="container">

    <%= yield %>
       
    <%= render 'layouts/footer' %>

  </div>

</body>
</html>

web_app/app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<% provide(:keywords, 'Tim Runcie, Rick Gardner, Cindy Lewis, Joe Brewer, Jeff Jacobson-Swartfager, Chetankumar Patel, Pam Greensky, Stacey Garner, Employees, Staff, Philosophy, Project Management') %>

<h1>About Us</h1>
<p>
  Advisicon delivers strategic project management solutions using advanced 
  project and portfolio management methodologies, custom application 
  development and comprehensive training. Our clients througout North and 
  Latin America have realized quantifiable results through our three unique
  philosophy tenets: knowledge transfer, optimization and sustained results.
</p>

<h2>Our Philosophy Defined</h2>
<dl>
  <div class="definitionItem">
    <dt>Optimization</dt>
    <dd>
      Advisicon integrates project management best practices along with 
      project management technologies to fit each client's organizational 
      structure, strategy and culture.
    </dd>
  </div>
  <div class="definitionItem">
    <dt>Knowledge Transfer</dt>
    <dd>
      Advisicon teaches clients to internalize and standardize project 
      management best practices and use of technology. Clients receive 
      task-specific coaching, in-depth process development, customized 
      project management methodology and supervised training with the 
      technology.
    </dd>
  </div>
  <div class="definitionItem">
    <dt>Sustained Results</dt>
    <dd>
      Through our phased approach, our clients are able to adopt and implement 
      strategic project management improvements, one step at a time. Clients 
      grow from one level of project management maturity to the next at their 
      own pace. Through this process of optimization and knowledge transfer, 
      Advisicon delivers sustained results to our clients.
    </dd>
  </div>
</dl>

<h2>How We Help</h2>
<p>
  Advisicon consultants can help your organization by effectively utilizing 
  business management technologies, such as Microsoft Project, Microsoft 
  Project Server and Microsoft SharePoint Server. Advisicon's solutions are 
  customized and designed to provide immediate and measurable results for all 
  levels of organizations. Advisicon has in-depth expertise with the latest 
  2013 suite of Microsoft project management products from training to 
  solution implementation and deployment.
</p>
<ul>
  <li>
    Custom Application Development (complex databases, integrations, reports, 
    workflows and dash-views)
  </li>
  <li>
    Enterprise-wide project resource and schedule visibility 
  </li>
  <li>
    Key business metrics analysis and reporting, and business intelligence
  </li>
  <li>
    Strategic aligning of initiatives with business objectives 
  </li>
  <li>
    Management dashboards with key performance indicators (KPIs)
  </li>
  <li>
    Align projects, programs, and portfolios with organizational priorities
  </li>
  <li>
    Customized, consultative instructor-led project management training
  </li>
</ul>

<h2>Our People</h2>
<p>
  Our team of professionals includes PMP<sup>&reg;</sup> certified project 
  managers, Microsoft Certified Professionals (with specializations in 
  Enterprise Project Management, Networking and Infrastructure Solutions), and 
  Microsoft  MVPs.
</p>

<!-- add employee list -->
<ul class="employee-list row">
  <li class="col-md-3 thumbnail"><a href='#'>
      <%= image_tag "tim-runcie.jpg" %>
      <span class="name">Tim Runice</span>
      <span class="title">President</span>
  </a></li>
  <li class="col-md-3 thumbnail"><a href='#'>
      <%= image_tag "rick-gardner.jpg" %>
      <span class="name">Rick Gardner</span>
      <span class="title">Director of Operations for Latin America</span>
  </a></li>
  <li class="col-md-3 thumbnail"><a href='#'>
      <%= image_tag "cindy-lewis.jpg" %>
      <span class="name">Cindy Lewis</span>
      <span class="title">Director of Knowledge Management</span>
  </a></li>
  <li class="col-md-3 thumbnail"><a href='#'>
      <%= image_tag "tye-trepanier.jpg" %>
      <span class="name">Tye Trepanier</span>
      <span class="title">Director of Advisicon Professional Services</span>
  </a></li>
  <li class="col-md-3 thumbnail"><a href='#'>
      <%= image_tag "jeff-jacobson-swartfager.jpg", alt: 'Jeff Jacobson-Swartfager' %>
      <span class="name">Jeff Jacobson-Swartfager</span>
      <span class="title">Advisicon Press</span>
  </a></li>
  <li class="col-md-3 thumbnail"><a href='#'>
      <%= image_tag "kristin-raglione.jpg" %>
      <span class="name">Kristin Raglione</span>
      <span class="title">Marketing Advisor</span>
  </a></li>
  <li class="col-md-3 thumbnail"><a href='#'>
      <%= image_tag "chetan-patel.jpg" %>
      <span class="name">Chetan Patel</span>
      <span class="title">Senior Developer</span>
  </a></li>
  <li class="col-md-3 thumbnail"><a href='#'>
      <%= image_tag "chris-pfenninger.jpg" %>
      <span class="name">Chris Pfenninger</span>
      <span class="title">Advisicon Information Services</span>
  </a></li>
  <li class="col-md-3 thumbnail"><a href='#'>
      <%= image_tag "pam-greensky.jpg" %>
      <span class="name">Pam Greensky</span>
      <span class="title">Operations</span>
  </a></li>
  <li class="col-md-3 thumbnail"><a href='#'>
      <%= image_tag "stacey-garner.jpg" %>
      <span class="name">Stacey Garner</span>
      <span class="title">Human Resources</span>
  </a></li>
</ul>

web_app/app/views/static_pages/careers.html.erb
<% provide(:title, 'Careers') %>
<% provide(:keywords, 'Job, Career, social media, marketing, IT, Project Management, Portfolio Management, Microsoft Project Server, Project Server, Microsoft SharePoint, EPM') %>
<h1>Careers</h1>
<p>Current openings:</p>
<ul>
  <li></li>
</ul>

web_app/app/views/users/new.html.erb
<% provide :title, 'Sign up' %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>